[platformio]
default_envs = uno, esp32dev, pico
src_dir = examples/TrafficLight

[env]
framework = arduino
lib_extra_dirs = .
build_flags = -Wall -Wextra

[env:uno]
platform = atmelavr
board = uno

[env:esp32dev]
platform = espressif32
board = esp32dev

[env:pico]
platform = raspberrypi
board = pico

[env:native]
platform = native
framework =
test_framework = custom
build_flags =
  -std=c++17
  -I test/test_native
lib_ignore = Unity
